### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by anseljh** [unitedstates/uslaw.link#1]
"502 Bad Gateway" :cry: 

![2016-01-22-502](https://cloud.githubusercontent.com/assets/2075772/12523801/ed550156-c10d-11e5-91ce-95a7b9d4a38e.png)

**Comment by JoshData** [comment]
Thanks! I just kicked it and it's back, and I added a thing to try to keep it running.

**Comment by anseljh** [comment]
:+1:

**Comment by mlissner** [comment]
> Thanks! I just kicked it and it's back, and I added a thing to try to keep it running.

Says every developer ever, every day ever.
